### ISSUE TITLE
week 01 回覆

### ISSUE THREAD

**Issue by azole** [y1lichen/git-practice#1]
「紀錄在 git repo 操作過程中，.git 檔案夾裡的變化」 這邊如果可以確實記錄到底看到了什麼，會更完整一些。

其他部分在 week 02 的課堂上有分享了，你可以再想想看，怎麼練習更深入地探討一個技術。

ps. 因為你的 email 被歸到垃圾信箱了，所以比較晚回覆，抱歉。

**Comment by y1lichen** [comment]
謝謝老師的回覆！我再記錄一些實驗截圖，這些新的commit會reference這個issue。

**Comment by azole** [comment]
謝謝你的回覆，也可以從之後的作業開始，記得要給自己進步的機會，持續改善，就會愈來愈強！

ps. 如果沒有其他需要跟我討論的事，這個 issue 可以 close 了。

**Comment by y1lichen** [comment]
收到！謝謝老師
